### ISSUE TITLE
additional URL for viasat plugin

### ISSUE THREAD

**Issue by nerijus** [chrippa/livestreamer#795] opened 2015-03-18 14:03 UTC
$ livestreamer http://play.tv3.lt/programos/keliukai/579347?autostart=true
error: No plugin can handle URL: http://play.tv3.lt/programos/keliukai/579347?autostart=true

$ livestreamer http://tv3play.lt/programos/keliukai/579347?autostart=true
[cli][info] Found matching plugin viasat for URL http://tv3play.lt/programos/keliukai/579347?autostart=true
Available streams: 576p (best, worst), medium

It would be nice if play.tv3.lt is added (it is the same as tv3play.lt).

**Comment by chrippa** [comment] 2015-03-22 16:50
Duplicate of #773.

**Closed by chrippa** 2015-03-22 16:50 UTC
