### ISSUE TITLE
Plug-in Request: Steam Broadcaster

### ISSUE THREAD

**Issue by xlegs** [chrippa/livestreamer#937] opened 2015-05-29 18:16 UTC
Steam Broadcaster would be a great plug-in to have for life streamer. Currently, Steam Broadcaster does not work on Firefox. Linux users are currently forced to use Google Chrome or the Steam client in order to watch the broadcast.

Here's an example link of such a broadcast.
http://steamcommunity.com/broadcast/watch/76561198198486997

Thanks

**Comment by VackerSimon** [comment] 2015-05-29 20:09
Duplicate of #621

**Closed** 2015-05-30 10:40 UTC
