### ISSUE TITLE
ard_live plugin currently not working

### ISSUE THREAD

**Issue by steave65** [chrippa/livestreamer#1353] opened 2016-06-12 14:03 UTC
Livestream-URL changed from:

live.daserste.de
to
daserste.de/live/index.html

is that the reason for: error: No plugin can handle URL: daserste.de/live/index.html ?

**Comment by dampfklon** [comment] 2016-06-12 18:31
workaround use following url http://www.ardmediathek.de/tv/Das-Erste/live?kanal=208

duplicate of #848

**Comment by MasterofJOKers** [comment] 2016-06-12 19:01
otherwise, this patch currently works:

``` patch
--- ard_live2.py    2016-06-12 20:54:57.510592060 +0200
+++ ard_live.py 2016-06-12 20:59:49.870581610 +0200
@@ -1,30 +1,26 @@
 import re
+from datetime import datetime

 from functools import partial

 from livestreamer.plugin import Plugin
 from livestreamer.plugin.api import http, validate
-from livestreamer.stream import HLSStream, HDSStream
+from livestreamer.stream import HDSStream


-STREAM_INFO_URL = "http://live.daserste.de/{0}/livestream.xml"
-SWF_URL = "http://live.daserste.de/lib/br-player/swf/main.swf"
-STREAMING_TYPES = {
-    "streamingUrlLive": (
-        "HDS", partial(HDSStream.parse_manifest, pvswf=SWF_URL)
-    ),
-    "streamingUrlIPhone": (
-        "HLS", HLSStream.parse_variant_playlist
-    )
-}
+STREAM_INFO_URL = "http://www.daserste.de/live/live-de-102~playerXml.xml?t={}"
+SWF_URL = "http://www.daserste.de/mediasrc/player/swf/main.swf"

-_url_re = re.compile("http(s)?://live.daserste.de/(?P<channel>[^/?]+)?")
+_url_re = re.compile("http(s)?://(?:www.)daserste.de/live/.*")

 _livestream_schema = validate.Schema(
-    validate.xml_findall("video/*"),
-    validate.filter(lambda e: e.tag in STREAMING_TYPES),
-    validate.map(lambda e: (STREAMING_TYPES.get(e.tag), e.text)),
-    validate.transform(dict),
+    validate.xml_findall("video/assets[2]/*[@type]"),
+    validate.filter(lambda e: 'HDS' in e.attrib['type']),
+    validate.map(lambda e: (
+                    ("HDS", partial(HDSStream.parse_manifest, pvswf=SWF_URL)),
+                    e.getchildren()[1].text
+                )),
+    validate.transform(dict)
 )

 class ard_live(Plugin):
@@ -33,9 +29,8 @@
         return _url_re.match(url)

     def _get_streams(self):
-        match = _url_re.match(self.url)
-        channel = match.group("channel")
-        res = http.get(STREAM_INFO_URL.format(channel))
+        url = STREAM_INFO_URL.format(datetime.now().strftime('%y-%m-%d-%H-%M'))
+        res = http.get(url)
         urls = http.xml(res, schema=_livestream_schema)

         streams = {}
```

**Comment by steave65** [comment] 2016-06-12 20:25
Ok, thanks for the qick reactions. :) And excuse my repost.

**Closed as completed** 2016-06-12 20:28 UTC
