### ISSUE TITLE
[Plugin request] Dota2.com

### ISSUE THREAD

**Issue by jeifour** [chrippa/livestreamer#1011] opened 2015-07-26 18:42 UTC
Website URL: http://www.dota2.com/watch/
Example stream URL: http://www.dota2.com/watch/76561198198486997

**Comment by intact** [comment] 2015-07-26 22:33
duplicate of #621

**Comment by jeifour** [comment] 2015-07-26 22:34
Ok didn't know that it's the same system.

**Closed** 2015-08-02 11:28 UTC
