### ISSUE TITLE
Cannot record live ustream in the best quality

### ISSUE THREAD

**Issue by ChoRyuJin** [chrippa/livestreamer#706] opened 2015-01-26 16:02 UTC
It seemed that Ustream had changed the setting.
I couldn't record live ustream in the best quality.
What errors got was:

![2015-01-16_210757](https://cloud.githubusercontent.com/assets/10710953/5902674/556fc42e-a5b7-11e4-8ba3-e96aec49e8a2.png)
[plugin.ustreamtv][error] Unable to fetch desktop streams: Failed to connect to RTMP server

It can only record the worst quality which is 240p.
Actually the stream broadcasted in 540p, even though it detected, but soon the cmd.exe disappeared and could not record in better quality.

Is it the problem with the plugin?

**Comment by k-ross** [comment] 2015-01-27 21:46
I get the same problem.  Sometimes it shows the list of streams properly, such as:
```
$ livestreamer http://www.ustream.tv/leolaporte
[cli][info] Found matching plugin ustreamtv for URL http://www.ustream.tv/leolaporte
Available streams: 240p, 240p_alt_akamai, 360p, 360p_alt_akamai, 480p, 480p_alt_akamai, 720p+ (best), 720p+_alt_akamai, mobile_240p (worst), mobile_360p, mobile_480p
```

and sometimes it fails to connect to the RTMP server, and I get a much smaller list of available streams:
```
$ livestreamer http://www.ustream.tv/leolaporte
[cli][info] Found matching plugin ustreamtv for URL http://www.ustream.tv/leolaporte
[plugin.ustreamtv][error] Unable to fetch desktop streams: Failed to connect to RTMP server
Available streams: mobile_240p (worst), mobile_360p, mobile_480p (best)
```

I'm using the latest from git, branch master.

**Comment by EraYaN** [comment] 2015-01-29 21:44
This bug is still there in the develop branch. I only get the mobile_240p. 
python-librtmp is installed (using the wheel) and rtmpdump is in my path.

http://ustream.tv/nasahdtv is always a good test stream because they are always live.

**Comment by xZise** [comment] 2015-01-31 14:35
Is there a way to get additional output to maybe have a better analysis? Because sometimes I don't even get the error and it still selects the mobile stream.

**Comment by EraYaN** [comment] 2015-01-31 15:14
Even the debug level log output is almost nothing.

**Comment by iz2lsc** [comment] 2015-01-31 19:56
In my case the streaming starts for less than 1 second and then stops



C:\Programmi\Livestreamer>livestreamer.exe www.ustream.tv/channel/14313537
[cli][info] Found matching plugin ustreamtv for URL www.ustream.tv/channel/14313537
[plugin.ustreamtv][debug] Waiting for moduleInfo invoke
[cli][info] Available streams: 240p, 240p_alt_akamai, 720p+ (best), 720p+_alt_akamai, mobile_240p (worst)
[cli][info] Opening stream: 720p+ (uhs)
[stream.uhs][debug] Fetching module info
[stream.uhs][debug] Stream went offline
[stream.uhs][debug] Closing worker thread
[cli][debug] Pre-buffering 8192 bytes
[stream.uhs][debug] Closing writer thread
[cli][error] No data returned from stream
[stream.uhs][debug] Fetching module info
[stream.uhs][debug] Adding chunk 1422725720 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.uhs][debug] Download of chunk 1422725720 complete
[cli][info] Starting player: "C:\Programmi\VideoLAN\VLC\vlc.exe"
[stream.uhs][debug] Fetching module info
[cli][debug] Writing stream to output
[stream.uhs][debug] Adding chunk 1422725721 to queue
[stream.uhs][debug] Download of chunk 1422725721 complete
[stream.uhs][debug] Fetching module info
[stream.uhs][debug] Stream went offline
[stream.uhs][debug] Closing worker thread
[stream.uhs][debug] Closing writer thread
[cli][info] Stream ended

C:\Programmi\Livestreamer>

**Comment by k-ross** [comment] 2015-01-31 20:05
The "unable to connect to RTMP server" problem seems to have resolved itself, but I can no longer get it to record more than a few seconds worth of video, before it exits, saying the stream went offline.

**Comment by EraYaN** [comment] 2015-01-31 20:13
@iz2lsc What build are you using my output is as follows:
>livestreamer.exe www.ustream.tv/channel/14313537
[cli][info] Found matching plugin ustreamtv for URL www.ustream.tv/channel/14313537
Available streams: mobile_240p (worst, best)

and the version:
>livestreamer --version
livestreamer-script.py 1.11.1

**Comment by iz2lsc** [comment] 2015-01-31 20:19
I'm also using version 1.11.1

**Comment by EraYaN** [comment] 2015-01-31 20:27
It's weird that I get different output..
I'm in the Netherlands (northern Europe).

Also I got the same output after I switched my rtmpdump version from:

>RTMPDump v2.4 GIT-2015-01-15 (Compiled by KSV)
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL

to 

>RTMPDump v2.4 GIT-2012-03-08 (Compiled by KSV)
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL


The newer one made it so that it couldn't detect any RTMP streams.

**Comment by iz2lsc** [comment] 2015-01-31 20:59
I think that if you try several times, you can get different results

**Comment by EraYaN** [comment] 2015-01-31 21:20
I'm just now looking in the viewer:303.swf the code (at least decompiled) is a MESS.

I think I found most of the streaming code inside scripts/tv/ustream/viewer/viewerloader (for the rsl stuff and some api?)
and scripts/tv/ustream/viewer/viewer (for most of the viewer setup and buildup to streaming. Didn't see any "real/raw" stream code, but I'm not really much of a ActionScript guy so maybe adobe code handles that.)

I was looking at their build from: 2015.01.27. 16:33:27,19 (from: scripts/tv/ustream/viewer/viewerversion)  But they rotate different viewer files for different channels and different times (to test stuff out). I got this one (303) from here: http://www.ustream.tv/channel/stolabo-tokyo but sometimes they give me viewerqos:14.swf

BTW I used FFdec (JPEXS FFDec 4.0.5)

**Comment by k-ross** [comment] 2015-02-01 05:49
I don't know if the author of livestreamer used decompiled code, or just analyzed the network stream with Wireshark and the like.  But if he reverse engineered it from analyzing the stream, having a peek at the decompiled flash player should help improve livestreamer.

I myself am also a software developer, and while I don't know ActionScript, I do have some experience with network streaming video, so I wouldn't mind having a peek at the decompiled code.  I might give that a try later tonight.

**Comment by k-ross** [comment] 2015-02-01 06:24
viewer:303.swf contains mostly UI code.  The actual logic for the video streaming is in viewer.rsl.swf, which you can download from http://www.ustream.tv/flash/viewer.rsl.swf

**Comment by iz2lsc** [comment] 2015-02-04 20:37
it seems there is no development on this topic. Somebody know an alternative to livestreamer?

Thanks

**Comment by ChoRyuJin** [comment] 2015-02-07 03:10
k-ross, how could I download from the swf viewer? Could you explain in details? Thank you.

**Comment by trUSTssc** [comment] 2015-02-16 12:33
AFAICT the source of the problem is that some of the Ustream RTMP servers are now sending 'moduleInfo' in AMF3. It looks like librtmp can not parse that correctly; only a fraction of the needed information is returned from AMF_Decode().

If you by chance happen to connect to an RTMP server that still(?) uses AMF0 and can keep using that server everything works as before.

**Comment by chrippa** [comment] 2015-03-01 19:34
Thanks for looking into this issue @trUSTssc, it was indeed a problem with AMF3. I've pushed a update that uses [python-flashmedia](/chrippa/python-flashmedia)'s  decoder instead of the one built into librtmp.

**Closed by chrippa** 2015-03-01 19:34 UTC
Labels: bug, plugin
