### ISSUE TITLE
Problem loading MLG.tv with Livestreamer.exe

### ISSUE THREAD

**Issue by KaDe-** [chrippa/livestreamer#685] opened 2015-01-14 22:22 UTC
Everytime i try to load any MLG stream threw livestreamer, it gives me the same error,
http://gyazo.com/c14e778982cbcca058906d8391265158
This never used to happen it just started yesterday at random, please help!

**Comment by skulblakka** [comment] 2015-01-14 22:28
Duplicate of #683

**Closed** 2015-01-15 19:02 UTC
