### ISSUE TITLE
Feature Request: Title name

### ISSUE THREAD

**Issue by ArchUser** [chrippa/livestreamer#760] opened 2015-02-25 21:04 UTC
Could we have an option for a title so if you have two stream they both don't have stdin title? I know I can save to disk change the title but it'd be nice if we can just set the title.

**Comment by chrippa** [comment] 2015-02-25 21:58
Duplicate of #194.

**Closed by chrippa** 2015-02-25 21:58 UTC

**Comment by ArchUser** [comment] 2015-02-25 22:01
Is there any timeline for this?
