### ISSUE TITLE
vaughnlive changes cause new problem

### ISSUE THREAD

**Issue by potentate** [chrippa/livestreamer#904] opened 2015-05-12 10:03 UTC
livestreamer http://vaughnlive.tv/newzviewz
[cli][info] Found matching plugin vaughnlive for URL http://vaughnlive.tv/newzviewz
error: Unable to validate response text: Minimum length is 2 but value is 1

**Comment by betagan** [comment] 2015-05-12 10:32
duplicate of #897 ?

should be fixed in 24805585ed0303a9ef84106e1919b1c396370119#diff-42b41f48ea37ae1e70234cbeea2675f1

**Comment by potentate** [comment] 2015-05-12 11:19
Yes, it works. Thanks!

**Comment by cloud90** [comment] 2015-05-12 13:35
how to make change in the file?

**Comment by potentate** [comment] 2015-05-12 13:40
see 
https://github.com/chrippa/livestreamer/commit/24805585ed0303a9ef84106e1919b1c396370119

**Comment by fadster** [comment] 2015-05-12 14:38
when can we expect an updated installer?

**Comment by skulblakka** [comment] 2015-05-12 15:10
Have you tried using the [nightly build](http://docs.livestreamer.io/install.html#nightly-build)?

**Comment by fadster** [comment] 2015-05-12 15:59
Thank you, I wasn't aware of them. It works! :)

**Closed** 2015-05-12 16:04 UTC
