### ISSUE TITLE
Feature request: Beam.pro

### ISSUE THREAD

**Issue by dminer78** [chrippa/livestreamer#884] opened 2015-05-02 22:08 UTC
Hello, there's a new livestreaming service almost like twitch.tv, but it's named beam.pro. They're a new streaming service which already have a lot ready for the future. Many people have already added Beam support and thought it would be useful to have this for livestreamer as well.

**Comment by chrippa** [comment] 2015-05-02 22:56
Duplicate of #771.

**Closed by chrippa** 2015-05-02 22:56 UTC
