### ISSUE TITLE
Twitch Client-ID Requirement

### ISSUE THREAD

**Issue by ThrowAwayAccount023948029834** [chrippa/livestreamer#1462] opened 2016-08-30 21:11 UTC
They finally implement the Client-ID Requirement? I'm getting this error now.

`livestreamer -p mpv twitch.tv/monstercat best
[cli][info] Found matching plugin twitch for URL twitch.tv/monstercat
error: Unable to open URL: https://api.twitch.tv/api/channels/monstercat/access_token.json (400 Client Error: Bad Request for url: https://api.twitch.tv/api/channels/monstercat/access_token.json?as3=t)`

**Comment by liz1rgin** [comment] 2016-08-30 21:53
i'm opened stream now, no problem

**Comment by skulblakka** [comment] 2016-08-31 17:14
Duplicate of #1456

**Closed** 2016-09-02 22:42 UTC
